# Generated by Django 4.2.7 on 2024-03-16 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^(8|\\+7)\n            \\s*[\\-]?\\s*(\n                (\\(\\d{3}\\)\\s*[\\-]?\\s*\\d{3}\\s*[\\-]?\\s*\\d{2}\\s*[\\-]?\\s*\\d{2})\n                |\n                (\\s*\\d{3}\\s*[\\-]?\\s*\\d{3}\\s*[\\-]?\\s*\\d{2}\\s*[\\-]?\\s*\\d{2}\\s*))$')])),
            ],
        ),
    ]
