# Generated by Django 4.2.7 on 2024-03-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_category_image_alter_course_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type_of_course',
            field=models.CharField(choices=[('A', 'Audio'), ('V', 'Video'), ('T', 'Text')], default='T', max_length=1),
        ),
    ]
