# Generated by Django 4.2.7 on 2024-03-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_question_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
